### ISSUE TITLE
Linker error

### ISSUE THREAD

**Issue by bavay** [gadomski/rivlib-utils#3]
Hi!
We have trouble compiling rivlib-utils with RiVLib 2.5.4 Linux gcc44:

CMakeFiles/ri-inclination.dir/src/app.cpp.o: In function `scanlib::basic_rconnection::create(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
app.cpp:(.text._ZN7scanlib17basic_rconnection6createERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES8_S8_[_ZN7scanlib17basic_rconnection6createERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES8_S8_]+0x20): undefined reference to `scanlib::basic_rconnection::create_impl(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
collect2: error: ld returned 1 exit status
CMakeFiles/ri-inclination.dir/build.make:126: recipe for target 'ri-inclination' failed
make[2]: *** [ri-inclination] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/ri-inclination.dir/all' failed
make[1]: *** [CMakeFiles/ri-inclination.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

Do we need to have scanlib in version 3.5.1? Do you have this version? (it is not available on Riegl's website)

Thanks,
Mathias

**Comment by gadomski** [comment]
I just tried to build against `rivlib-2_5_4-x86_64-linux-gcc44` with gcc 5.4.0, and got a similar error. Make sure your gcc version matches your rivlib gcc version. There's a version of RiVLib 2.5.4 built for gcc-5 (`rivlib-2_5_4-x86_84-linux-gcc55`) available from the Riegl website. I'd try building against that, and do let me know how it goes. Or your could use gcc 4 with your current version of rivlib, either way...

> Do we need to have scanlib in version 3.5.1?

As far as I can tell, 2.5.4 is the newest version on the Riegl website, as of this writing.

**Comment by gadomski** [comment]
Closing as noresponse.
