### ISSUE TITLE
Right RiVLib path?

### ISSUE THREAD

**Issue by plitkey** [gadomski/rivlib-utils#4]
Thanks for the utils, I had minor problem, probably there has been change in the library structure or something. My version was rivlib-2_5_7-x86_64-linux-gcc55

cmake .. -G "Unix Makefiles" -DRiVLib_DIR=/path/to/your/rivlib-2_5_7-x86_64-linux-gcc55

there was warning "By not providing "FindRiVLib.cmake" in CMAKE_MODULE_PATH this project has  asked CMake to find a package configuration file provided by "RiVLib", but CMake did not find one." 

I gave  

cmake .. -G "Unix Makefiles" -DRiVLib_DIR=/path/to/your/rivlib-2_5_7-x86_64-linux-gcc55/cmake

and the compilation finished and I was able to make install. And run the utils codes.

**Comment by gadomski** [comment]
Yup, that's a mistake in the documentation, fixed. Thanks!
