### ISSUE TITLE
Can we quickly get the specified information from the rxp file through RIVLIB ?

### ISSUE THREAD

**Issue by threeflowermeow** [gadomski/rivlib-utils#5]
Hi,
For example, enter the GPS time and quickly retrieve a pointcloud class without having to traverse the entire rxp file ?

**Comment by gadomski** [comment]
`rxp` files don't have an index, so the best you could do would be to read through the file until you find a matching GPS time (e.g.) and then return the corresponding data. Pull requests welcome!
